services:

  redis:
    image: "redis:latest"
    container_name: "redis-erp"
    ports:
      - "6379:6379"
    volumes:
      - ./extras/redis-data:/data

  postgres:
    image: postgres:latest
    container_name: roteiro-postgres
    environment:
      - POSTGRES_DB=roteiro-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sHDv7kCSisihnOfS3l7k
    ports:
      - "5432:5432"
    volumes:
      - ./extras/postgres_db:/var/lib/postgresql/data

  minio:
    image: "quay.io/minio/minio"
    container_name: "minio-erp"
    environment:
      MINIO_ROOT_USER: "lfpo2005"
      MINIO_ROOT_PASSWORD: "197197197"
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./extras/minio-data:/data